# Generated by Django 5.1.1 on 2024-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('TraineeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('ContactNo', models.CharField(max_length=15)),
                ('ContactAddress', models.CharField(max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('BatchNo', models.CharField(default='N\\A', max_length=30)),
            ],
            options={
                'db_table': 'Trainee',
            },
        ),
    ]
