# Generated by Django 5.1.1 on 2024-09-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleApp01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='TraineeID',
            new_name='TraineeId',
        ),
    ]
